export const environment = {
  production: false,
  suchDogeApi: "http://localhost:8080",
  authPrefix: "Bearer ",
  authHeader: "Authorization",
  authTokenKey: "dogeAuthToken",
  refreshPrefix: "Bearer ",
  refreshHeader: "Authorization-Refresh",
  refreshTokenKey: "dogeAuthRefreshToken",
  preferredThemeKey: "dogePreferredTheme",
  defaultMemePageSize: 8,
  minUsernameLength: 3,
  maxUsernameLength: 36,
  minEmailLength: 3,
  maxEmailLength: 254,
  minPasswordLength: 6,
  maxPasswordLength: 50,
  newRequestDateKey: "dogeNewRequestDateKey",
  imageUrlPrefix: "https://suchdoge-storage-dev.s3.amazonaws.com"
};
