export const environment = {
  production: false,
  suchDogeDomain: "localhost:8080",
  suchDogeApiDomain: "localhost:8080",
  suchDogeApiUrl: "http://localhost:8080",
  suchDogeCdnUrl: "https://suchdoge-storage-dev.s3.amazonaws.com",
  authPrefix: "Bearer ",
  authHeader: "Authorization",
  authTokenKey: "dogeAuthToken",
  refreshPrefix: "Bearer ",
  refreshHeader: "Authorization-Refresh",
  refreshTokenKey: "dogeAuthRefreshToken",
  preferredThemeKey: "dogePreferredTheme",
  defaultMemePageSize: 8,
  minUsernameLength: 3,
  maxUsernameLength: 36,
  minEmailLength: 3,
  maxEmailLength: 254,
  minPasswordLength: 6,
  maxPasswordLength: 50,
  newRequestDateKey: "dogeNewRequestDateKey",
  chainSoUrlPrefix: "https://chain.so/address",
  qrGeneratorUrlPrefix: "https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl="
};
